# Generated by Django 5.1.7 on 2025-03-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_chathistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='msg',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
