# Generated by Django 5.1.7 on 2025-03-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='titel',
            new_name='title',
        ),
        migrations.AddField(
            model_name='lesson',
            name='estimated_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
