# Generated by Django 5.1.7 on 2025-03-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_titel_lesson_title_lesson_estimated_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='estimated_time',
            field=models.CharField(max_length=100),
        ),
    ]
